In [14]:
import numpy as np #linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('../../../CSV/Social_Network_Ads.csv')

In [16]:
df = df.iloc[:,2:]

In [17]:
df.sample(5)

     Age  EstimatedSalary  Purchased
126   42            65000          0
348   39            77000          0
95    35            44000          0
386   49            39000          1
188   35            72000          0

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('Purchased', axis=1),
                                                    df['Purchased'],
                                                    test_size=0.3,
                                                    random_state=0)
x_train.shape, x_test.shape

((280, 2), (120, 2))

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [20]:
x_test_scaled

array([[-0.77101313,  0.49720103],
       [ 0.0133054 , -0.57280368],
       [-0.28081405,  0.15017248],
       [-0.77101313,  0.26584866],
       [-0.28081405, -0.57280368],
       [-1.06513258, -1.44037507],
       [-0.67297331, -1.5849703 ],
       [-0.18277423,  2.14558666],
       [-1.94749093, -0.05226085],
       [ 0.89566375, -0.775237  ],
       [-0.77101313, -0.60172273],
       [-0.96709276, -0.42820845],
       [-0.08473441, -0.42820845],
       [ 0.11134522,  0.20801057],
       [-1.7514113 ,  0.46828198],
       [-0.5749335 ,  1.36477242],
       [-0.08473441,  0.20801057],
       [-1.84945111,  0.43936294],
       [ 1.67998229,  1.74072002],
       [-0.28081405, -1.38253697],
       [-0.28081405, -0.65956082],
       [ 0.89566375,  2.14558666],
       [ 0.30742485, -0.54388463],
       [ 0.89566375,  1.01774386],
       [-1.45729185, -1.2090227 ],
       [ 1.09174339,  2.05882953],
       [-0.96709276,  0.49720103],
       [-0.86905295,  0.29476771],
       [-0.08473441, -0.22577513],
       [-0.5749335 ,  0.46828198],
       [-1.65337148,  0.52612008],
       [-0.08473441,  0.26584866],
       [ 1.87606192, -0.28361322],
       [-0.08473441, -0.48604654],
       [-1.35925203, -0.34145131],
       [-1.94749093, -0.51496559],
       [-1.55533166,  0.32368675],
       [-0.37885386, -0.775237  ],
       [-0.67297331, -1.03550842],
       [ 1.09174339, -0.97767033],
       [-1.06513258,  0.52612008],
       [ 0.30742485, -0.51496559],
       [-1.06513258,  0.41044389],
       [-0.28081405, -1.44037507],
       [ 0.50350449,  1.22017719],
       [-1.06513258, -0.34145131],
       [-0.08473441,  0.29476771],
       [ 1.38586284,  0.58395817],
       [-1.1631724 , -1.1511846 ],
       [ 1.09174339,  0.46828198],
       [ 1.87606192,  1.50936765],
       [-0.37885386, -1.29577984],
       [-0.28081405, -0.37037036],
       [-0.37885386,  1.30693432],
       [ 2.07214155,  0.52612008],
       [ 0.69958412, -1.09334651],
       [-0.86905295,  0.38152485],
       [-1.1631724 ,  0.29476771],
       [ 1.09174339, -1.2090227 ],
       [-1.45729185, -1.44037507],
       [-0.5749335 , -1.49821316],
       [ 2.17018137, -0.80415605],
       [-1.84945111,  0.17909152],
       [-0.18277423,  0.84422958],
       [-1.84945111, -1.26686079],
       [ 2.17018137,  0.38152485],
       [-1.35925203,  0.55503912],
       [-1.06513258, -0.34145131],
       [ 0.20938504, -0.65956082],
       [ 0.40546467,  0.00557724],
       [-0.5749335 ,  2.31910094],
       [-0.28081405,  0.20801057],
       [-1.55533166, -0.19685608],
       [ 0.69958412, -1.38253697],
       [-1.06513258,  0.55503912],
       [-1.94749093,  0.3526058 ],
       [ 0.40546467,  0.26584866],
       [ 0.20938504, -0.28361322],
       [ 1.48390265, -1.03550842],
       [ 0.89566375,  1.07558195],
       [ 1.97410174,  2.14558666],
       [ 2.07214155,  0.38152485],
       [-1.35925203, -0.42820845],
       [-1.1631724 , -1.00658937],
       [ 1.97410174, -0.91983223],
       [ 0.40546467,  0.29476771],
       [ 0.20938504,  0.15017248],
       [ 2.07214155,  1.74072002],
       [ 0.79762394, -0.8330751 ],
       [ 0.30742485, -0.28361322],
       [ 0.40546467, -0.16793703],
       [-0.08473441,  2.20342476],
       [-1.45729185, -0.63064177],
       [-1.26121221, -1.06442747],
       [-1.35925203,  0.41044389],
       [-1.06513258,  0.75747245],
       [-1.45729185, -0.19685608],
       [ 0.99370357, -1.06442747],
       [ 0.99370357,  0.58395817],
       [ 0.40546467,  0.98882482],
       [ 0.6015443 , -0.89091319],
       [-0.5749335 ,  1.45152956],
       [ 0.0133054 , -0.57280368],
       [-0.5749335 ,  1.88531525],
       [ 1.38586284, -1.41145602],
       [ 1.48390265,  0.98882482],
       [ 0.11134522, -0.80415605],
       [ 0.0133054 , -0.25469417],
       [-0.18277423, -0.57280368],
       [-0.18277423, -0.19685608],
       [-0.28081405, -1.29577984],
       [-0.28081405, -0.57280368],
       [ 0.40546467,  0.09233438],
       [ 0.89566375, -0.60172273],
       [ 2.07214155, -1.18010365],
       [ 1.09174339, -0.13901799],
       [ 0.69958412,  1.76963906],
       [-0.67297331,  0.55503912],
       [ 0.79762394,  0.3526058 ],
       [ 0.89566375, -0.54388463]])

In [21]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

np.round(x_train.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [22]:
x_test_scaled

          Age  EstimatedSalary
0   -0.771013         0.497201
1    0.013305        -0.572804
2   -0.280814         0.150172
3   -0.771013         0.265849
4   -0.280814        -0.572804
..        ...              ...
115  1.091743        -0.139018
116  0.699584         1.769639
117 -0.672973         0.555039
118  0.797624         0.352606
119  0.895664        -0.543885

[120 rows x 2 columns]

In [23]:
# why scaling is important

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr_scaled = LogisticRegression()

lr.fit(x_train,y_train)
lr_scaled.fit(x_train_scaled,y_train)

LogisticRegression()

y_prep = lr.predict(x_test)
y_prep_scaled = lr_scaled.predict(x_test_scaled)

In [24]:
from sklearn.metrics import accuracy_score

print("Actual", accuracy_score(y_test,y_prep))
print("Scaled", accuracy_score(y_test,y_prep_scaled))

Actual 0.875
Scaled 0.8666666666666667